'use client';
import { useEffect, useRef, useState } from 'react';
import { Pause, Play, RotateCcw, Focus, HardHat, ChevronDown, ChevronUp, VolumeX, Sun, Check, Box, ArrowUpRight, MousePointer2, Package, Settings2, BrickWall, Hammer, Wrench } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { registerSimulationTools } from '@/lib/construction/webmcp';
import { Simulation, STAGES, type WorkerState } from '@/lib/construction/simulation';
const ROLE_ICONS=[Package,Settings2,BrickWall,Hammer,Wrench];
const STATE:Record<WorkerState,string>={supporting:'搬运材料',unloadTrip:'下车转运材料',fetching:'前往取料',handcarry:'搬运材料',loading:'装车取料',unloading:'卸下材料',toCart:'返回推车',toControl:'前往控制台',operating:'运输材料',mixing:'运输混凝土',movingWork:'前往运料',waitingSupply:'盘点补料',waitingPartner:'协同搬运',idle:'接受任务',material:'前往材料区',carrying:'搬运材料',working:'正在施工',returning:'搬往建筑',waiting:'转派任务中',finished:'施工完成'};
const clock=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
export default function Home(){
 const host=useRef<HTMLDivElement>(null);const sim=useRef<Simulation|null>(null);const world=useRef<{resetView:()=>void;dispose:()=>void}|null>(null);const [epoch,setEpoch]=useState(0);const [,update]=useState(0);const [ready,setReady]=useState(false);const [error,setError]=useState('');const [expanded,setExpanded]=useState(false);
 useEffect(()=>{let gone=false;setReady(false);setError('');const s=new Simulation();sim.current=s;const unregister=registerSimulationTools(s,()=>update(x=>x+1));import('@/lib/construction/scene').then(({createWorld})=>{if(gone||!host.current)return;try{world.current=createWorld(host.current,s,()=>update(x=>x+1));setReady(true);}catch(e){setError(e instanceof Error&&/WebGL|context/i.test(e.message)?'浏览器暂不支持 WebGL，请开启硬件加速后重试。':'场景初始化失败，请重新加载。');console.error(e);}}).catch(e=>{setError('场景加载失败，请刷新重试。');console.error(e);});return()=>{unregister();gone=true;world.current?.dispose();world.current=null;};},[epoch]);
 const s=sim.current;const stage=s?.stage??0;const progress=(s?.progress??0)*100;const paused=s?.paused??false;const working=s?.workers.filter(w=>w.state!=='finished').length??5;
 const inventory=s?.inventory??[];const totals=inventory.reduce((a,v)=>({stock:a.stock+v.stock,transit:a.transit+v.transit,site:a.site+v.site,installed:a.installed+v.installed}),{stock:0,transit:0,site:0,installed:0});
 return <main className="workbench">
  <div ref={host} className="scene" aria-label="可旋转缩放的三维建筑工地" />
  <header className="masthead"><div className="identity"><div className="brand-icon"><Box size={26} strokeWidth={1.4}/></div><div><div className="eyebrow">LITTLE BUILDERS</div><h1>筑城之间<span>自动建造演示</span></h1></div></div><div className="weather"><Sun size={19}/><span>晴朗 <b>24°</b></span><span className="separator"/><span className="live-state"><i className={paused?'paused':''}/>{s?.complete?'已竣工':paused?'已暂停':'建造进行中'}</span></div></header>
  <section className="project-card"><div className="project-kicker"><span>PROJECT 001</span><span className="project-label">两层办公楼</span></div><h2>{s?.complete?'一砖一瓦，已成新家。':'从一片空地开始。'}</h2><p>五位工人，一栋房子。看建造慢慢发生。</p><div className="project-stats"><div><strong>{Math.round(progress)}<small>%</small></strong><span>建造进度</span></div><div><strong>{clock(s?.time??0)}</strong><span>工地时间</span></div><div><strong>5<small> 人</small></strong><span>施工团队</span></div></div><Progress value={progress} aria-label="建造总进度" className="build-progress"/><div className="current-stage"><span>{s?.complete?<Check size={14}/>:<span className="stage-pulse"/>}{s?.complete?'建造完成':STAGES[stage]}</span><span>{Math.min(stage+1,8)} / 8</span></div><details className="inventory-panel" open><summary>材料库存 <span>{totals.stock} 组剩余</span></summary><div className="inventory-grid">{inventory.map(item=><div key={item.kind}><span>{item.name}</span><strong>{item.stock}<small> / 备 {item.initial}</small></strong><em>建筑需 {item.required} · 余量 {item.surplus}</em><Progress value={item.stock/item.initial*100} aria-label={`${item.name}库存`} className="stock-progress"/></div>)}</div><div className="material-flow"><span>运输 {totals.transit}</span><span>待用 {totals.site.toFixed(1)}</span><span>已装 {totals.installed.toFixed(1)}</span></div><p className="material-note">场内 1 个模型 = 1 组库存；备料为建筑所需加明确余量</p></details><div className="delivery-event">{s?.events[0]}</div></section>
  <aside className={`crew-card ${expanded?'':'collapsed'}`}><button className="crew-heading" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}><span><HardHat size={18}/>施工队 <small>05</small></span>{expanded?<ChevronUp size={17}/>:<ChevronDown size={17}/>}</button>{expanded&&<><div className="crew-summary">{s?.complete?'施工完成':`${working} 人参与当前施工链`}</div><div className="crew-list">{(s?.workers??[]).map(w=>{const RoleIcon=ROLE_ICONS[w.id];return <div key={w.id} className="crew-row"><span className="worker-avatar" style={{'--worker':w.color} as React.CSSProperties}><RoleIcon size={21}/><small>{String(w.id+1).padStart(2,'0')}</small></span><div className="worker-details"><div><b>{w.role} {String(w.id+1).padStart(2,'0')}</b><span className={`state ${w.state}`}>{STATE[w.state]}</span></div><p>{s?.task(w)?.label??(w.state==='finished'?'房屋已交付':'正在转派当前工序')}</p></div></div>})}</div><div className="crew-foot"><span>已完成 {s?.crane.lifts??0} 次高层吊装</span><span>HOUSE–001 <ArrowUpRight size={12}/></span></div></>}</aside>
  <div className="stage-track" aria-label="施工阶段">{STAGES.map((label,i)=><div className={`${i<stage?'done':''} ${i===stage?'active':''}`} key={label}><span>{i<stage?<Check size={12}/>:String(i+1).padStart(2,'0')}</span><b>{label}</b></div>)}</div>
  <div className="scene-caption"><span className="caption-line"/><span>一座小小的世界，正在生长。</span></div>
  <footer className="bottom-bar"><div className="mouse-help"><MousePointer2 size={15}/><span>拖动旋转 · 滚轮缩放 · 右键平移</span></div><div className="controls"><button className="play-button" disabled={!ready} onClick={()=>{if(s)s.paused=!s.paused;update(x=>x+1);}} aria-label={paused?'继续建造':'暂停建造'}>{paused?<Play size={17} fill="currentColor"/>:<Pause size={17} fill="currentColor"/>}<span>{paused?'继续':'暂停'}</span></button><div className="speeds" aria-label="模拟速度">{[1,2,4].map(speed=><button key={speed} aria-pressed={s?.speed===speed} className={s?.speed===speed?'selected':''} onClick={()=>{if(s)s.speed=speed;update(x=>x+1);}}>{speed}×</button>)}</div><span className="control-divider"/><button className="icon-button" aria-label="恢复视角" title="恢复视角" onClick={()=>world.current?.resetView()}><Focus size={19}/></button><AlertDialog><AlertDialogTrigger asChild><button className="icon-button" aria-label="重新建造" title="重新建造"><RotateCcw size={17}/></button></AlertDialogTrigger><AlertDialogContent className="reset-dialog"><AlertDialogTitle>重新开始建造？</AlertDialogTitle><AlertDialogDescription>当前施工进度将清空，五名工人会从基础作业重新开始。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>继续观看</AlertDialogCancel><AlertDialogAction onClick={()=>setEpoch(x=>x+1)}>重新建造</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div><div className="local-note"><VolumeX size={14}/><span>本地演示 · 刷新后重新开始</span></div></footer>
  {!ready&&<div className="loading-panel" role="status"><Box size={28}/><h2>{error?'暂时无法进入工地':'正在准备工地'}</h2><p>{error||'安放地形、材料和五顶安全帽…'}</p>{error&&<button onClick={()=>setEpoch(x=>x+1)}>重新加载</button>}</div>}
 </main>;
}
